### ISSUE TITLE
I don't know what Markbot is trying to tell me?

### ISSUE THREAD

**Issue by NikCasar** [NikCasar/accessibility-fixer-upper#1]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/55094132/78930864-ccdb3580-7a72-11ea-8d3c-f4132b06999c.png">

so markbot keeps saying this but I have id tags for each of the sections already, im not really sure what it wants me to do? -nikki 

@muxlowc
@mackenzierose

**Comment by muxlowc** [comment]
@NikCasar  are those the only issues you're getting?

I figured out that Markbot actually has a typo (asking your about to go to contact lol).. so let me know when you've solved all other issues, and I will give you the mark!

**Comment by NikCasar** [comment]
So I did as much as I could and this is what markbot says now. -nikki 
<img width="497" alt="Screen Shot 2020-04-11 at 1 36 15 PM" src="https://user-images.githubusercontent.com/55094132/79050670-a72c6880-7bf9-11ea-8dfd-1237838cbb28.png">

@muxlowc

**Comment by muxlowc** [comment]
@NikCasar  

1) that first shrubs issue is because you have a capitalized S "...href="#Shrubs">"  so change that to a lowercase s 

That might solve your second issue as well

**Comment by MacKenzieRose** [comment]
If this issue has been addressed, please make sure to close it 😄

**Comment by NikCasar** [comment]
oh im so sorry, this was from last year i forgot about it.
